Update README.md
cptpiepmatz/nu-plugin-highlight pull request #4
Opened 2023-07-30 15:21 UTC by cig0

Add the new way to define environment variables starting with Nushel v0.83, as stated in https://www.nushell.sh/blog/2023-07-25-nushell_0_83.html#breaking-changes

2023-07-30 16:08 UTC, cptpiepmatz commented
Thank you for update on the README!

I totally forgot about the change despite having to deal with it in my own config. 😅

Although I kinda dislike how the default still says `let-env` and only the note clarifies this. I think it woul be better to update all the settings shell lines to `$env.{...}` and maybe add a note that explains that previously it used to be `let-env`. Nushell will already print the deprecation warning/error so we don't really need to do this here. It should be easy to users to just copy the shell lines.

2023-07-30 16:10 UTC, cptpiepmatz requested changes
Thank you for update on the README!

I totally forgot about the change despite having to deal with it in my own config. 😅

Although I kinda dislike how the default still says `let-env` and only the note clarifies this. I think it woul be better to update all the settings shell lines to `$env.{...}` and maybe add a note that explains that previously it used to be `let-env`. Nushell will already print the deprecation warning/error so we don't really need to do this here. It should be easy to users to just copy the shell lines.

2023-07-30 21:49 UTC, cig0 commented
I was unsure what approach you'd prefer -- %100 with you. Let me try something else.

2023-07-31 07:06 UTC, cptpiepmatz approved these changes
I like that, thanks!

2023-07-31 07:06 UTC, merged